# Generated by Django 5.0.4 on 2024-04-29 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_support_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support_messages',
            new_name='Support_message',
        ),
    ]
