# Generated by Django 5.0.4 on 2024-05-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='img',
            field=models.ImageField(default='default-user.jpg', upload_to='photos/'),
        ),
    ]
